### ISSUE TITLE
Current Overrides.toml instructions do not work - update README

### ISSUE THREAD

**Issue by hiemstar** [JuliaInterop/libcxxwrap-julia#99]
The content of the suggested Overrides.toml  is not correct. I was getting an init-error, see
[discourse.julialang](https://discourse.julialang.org/t/initerror-could-not-load-library-libcxxwrap-julia-stl-dll-on-windows/74535). The solution of the issue is also there.

It would be good to update the README.

**Comment by barche** [comment]
Hi, I can't reproduce this, for me this overrides file works:

```toml
[3eaa8342-bff7-56a5-9981-c04077f7cee7]
libcxxwrap_julia = "C:/Users/user/source/repos/libcxxwrap-julia/build"
```

Can you please give the complete path to the `libcxxwrap_julia.dll` that is built? Note that you should use the latest libcxxwrap-julia main, this also works with Julia 1.7 now.
